version: "3.8"

services:
    pgsql: # docker-compose exec -it pgsql bash
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: cloud
        ports:
            - "5438:5432"
        volumes:
            - ./.docker/pgsql/data:/var/lib/postgresql/data
    php: # docker-compose exec -it php bash
        build: './.docker/php'
        ports:
            - "8811:80"
        tty: true
        environment:
            PHP_IDE_CONFIG: "serverName=PbCloud_Local_Docker"
        volumes:
            - ./:/var/www/html/
            - ./.docker/php/logs/:/var/log/apache2/
            - ./.docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
            - ./.docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
        extra_hosts:
            - "host.docker.internal:host-gateway"
        depends_on:
            - pgsql
    composer: # docker-compose exec -it composer bash
        build: './.docker/composer'
        tty: true
        command: [ "composer", "update" ]
        volumes:
            - ./:/app/
            - ./.docker/composer/tmp/:/tmp/
        depends_on:
            - php
